config/routes.rb
Rails.application.routes.draw do
  root to: 'suppliers#index'
  resources :suppliers do
    resources :invoices, shallow: true
  end

  # Render the invoice page
  get '/pay-invoice/', to: 'invoices#payment'
  get '/payment/', to: 'invoices#pay'
  get '/transfers/', to: 'invoices#transfers'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :supplier
  enum pay_status: [:unpaid, :paid]
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :invoices

  validates :name, presence: true

  validates :bank_name,
            presence: true

  validates :account_number, presence: true,
            length: { minimum: 10,
                      maximum: 10,
                      message: 'Please insert the NUBAN account number.' }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy, :payment, :pay]

  # GET /invoices
  # GET /invoices.json
  def index
   if  params[:supplier_id].present?
     @invoices = Supplier.find(params[:supplier_id]).invoices
   else
     @invoices = Invoice.all
   end
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # Render Payment page
  def payment
    @supplier = @invoice.supplier
     render 'payment'
  end

  # All transfers
  def transfers
    @transfers = Payment.new.get_transfers
    @transfers
  end

  # Pay invoice off
  def pay
    @supplier = @invoice.supplier
    @account_details = Payment.new.create_transfer(@supplier.recipient_code,
                                                   @invoice.amount)
    if @account_details['data']['status'] == 'success'
      @invoice.update(:pay_status => 1)
      redirect_to supplier_invoices_path(:supplier_id => @supplier.id), notice: 'Invoice is being processed.'
    else
      render payment, notice: "Transfer not complete. Reason #{@account_details['message']}"
    end
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to supplier_invoices_path, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to suppliers_path, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:amount, :supplier_id, :pay_status)
    end
end
# Thou shall not scaffold blindly

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :set_supplier, only: [:show, :edit, :update, :destroy]

  # GET /suppliers
  # GET /suppliers.json
  def index
    @suppliers = Supplier.all
  end

  # GET /suppliers/1
  # GET /suppliers/1.json
  def show
    @supplier
  end

  # GET /suppliers/new
  def new
    @banks = Payment.new
    @bank_names = @banks.get_banks
    @supplier = Supplier.new
  end

  # GET /suppliers/1/edit
  def edit
    @bank_names = Payment.new.get_banks
  end

  # POST /suppliers
  # POST /suppliers.json
  def create
    @supplier = Supplier.new(supplier_params)
    @recipient = Payment.new.create_recipient(supplier_params[:name],
                                              supplier_params[:account_number],
                                              supplier_params[:bank_name])
    # Add the created recipient on PayStack.
    @supplier.recipient_code = @recipient['data']['recipient_code']

    respond_to do |format|
      if @supplier.save && @recipient['status'] == true
        format.html { redirect_to @supplier, notice: 'Supplier was successfully created.' }
        format.json { render :show, status: :created, location: @supplier }
      else
        format.html do  redirect_to new_supplier_url,
                                    notice: "There were errors saving you supplier. #{@recipient['message']}"
        end
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /suppliers/1
  # PATCH/PUT /suppliers/1.json
  def update
    respond_to do |format|
      if @supplier.update(supplier_params)
        format.html { redirect_to @supplier, notice: 'Supplier was successfully updated.' }
        format.json { render :show, status: :ok, location: @supplier }
      else
        format.html { render :edit }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suppliers/1
  # DELETE /suppliers/1.json
  def destroy
    @supplier.destroy
    respond_to do |format|
      format.html { redirect_to suppliers_url, notice: 'Supplier was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supplier
      @supplier = Supplier.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def supplier_params
      params.require(:supplier).permit(:name, :account_number, :bank_name, :contact)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
  def paid_invoice(invoice)
    if invoice.pay_status == 'paid'
      'Paid'
    else
      link_to 'Pay', pay_invoice_path(:id => invoice.id)
    end
  end
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/invoices/_form.html.erb
 <% if @invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% @invoice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <input type="hidden" name="supplier_id" id="supplier_id" value=<%= params[:supplier_id] %> />
  </div>
  <div class="field">
    <%= f.label :amount %>
    <%= f.text_field :amount, required: true %>
    <%= f.select :pay_status, %w(unpaid paid) %>
    <%= f.hidden_field :supplier_id, value: "#{Supplier.find(params[:supplier_id]).id.to_i}" %>
  </div>
  <div class="actions">
    <%= f.submit 'Create Invoice' %>
  </div>

app/views/invoices/edit.html.erb
<h1>Editing Invoice</h1>

<%= form_with(model: @invoice, url: invoice_path, method: :put, local: true) do |f| %>
 <%= render 'form', f:f %>
<% end %>
<%= link_to 'Show', @invoice %>

app/views/invoices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Invoices</h1>

<table>
  <thead>
    <tr>
      <th colspan="1"> Supplier</th>
      <th colspan="1"> Amount</th>
      <th colspan="1"> Status</th>
      <th colspan="3"> Actions</th>

    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.supplier.name %></td>
        <td><%= invoice.amount %></td>
        <td><%= invoice.pay_status %></td>
        <td><%= paid_invoice(invoice) %></td>
        <td><%= link_to 'Edit', edit_invoice_path(:id => invoice.id, :supplier_id => params[:supplier_id]) %></td>
        <td><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'All transfers', transfers_path %>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= form_with(model: @invoice, url: supplier_invoices_path, local: true) do |f| %>
  <%= render 'form', f:f %>
<% end %>

app/views/invoices/payment.html.erb
<h1>Pay Supplier</h1>

<p id="notice"><%= notice %></p>

<table>
  <thead>
  <tr>
    <th colspan="1"> Supplier Name</th>
    <th colspan="1"> Bank </th>
    <th colspan="1">  Amount</th>
    <th colspan="2">  Action</th>

  </tr>
  </thead>

  <tbody>
  <tr>
    <td><%= @supplier.name %></td>
    <td><%= @supplier.account_number %></td>
    <td><%= @invoice.amount %></td>

    <td><%= link_to 'Pay Invoice', payment_url(:id => @invoice.id) %></td>
  </tr>

  </tbody>
</table>
<%= link_to 'Edit', edit_supplier_path(@supplier) %> |
<%= link_to 'Back', suppliers_path %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>
<table>
  <thead>
  <tr>
    <th colspan="1"> Supplier</th>
    <th colspan="1"> Amount</th>
    <th colspan="1">Status</th>
    <th colspan="2"> Actions</th>
  </tr>
  </thead>

  <tbody>
  <tr>
    <td><%= @invoice.supplier.name %></td>
    <td><%= @invoice.amount %></td>
    <td><%= @invoice.pay_status %></td>
    <td><%= link_to 'Destroy', @invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>

  </tbody>
</table>
<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoice_path %>

app/views/invoices/transfers.html.erb
<h2> Your Paystack transfers. </h2>

<table>
  <thead>
  <tr>
    <th colspan="1"> Supplier Name </th>
    <th colspan="1"> Amount </th>
    <th colspan="1">  Date </th>
    <th colspan="1">  Reference </th>

  </tr>
  </thead>

  <tbody>
  <% @transfers.each do | transfer | %>
  <tr>
    <td><%= transfer['recipient']['name'] %></td>
    <td><%= transfer['amount']/100 %></td>
    <td><%= transfer['createdAt'] %></td>
    <td><%= transfer['reference'] %></td>
  </tr>
  <% end %>
  </tbody>
</table>

<br>
<%= link_to 'All suppliers', suppliers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SupplyPay</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/suppliers/_form.html.erb
<%= form_with(model: supplier, local: true) do |f| %>
  <% if @supplier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@supplier.errors.count, "error") %> prohibited this supplier from being saved:</h2>

      <ul>
      <% @supplier.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true %>
  </div>

  <div class="field">
    <%= f.label :account_number %>
    <%= f.text_field :account_number, required: true, maxlength: 10 %>
  </div>

  <!-- TODO: Populate select menu with list of banks PayStack supports. -->
  <div class="field">
    <%= f.label :bank_name %>
    <%= f.select 'bank_name',
                 options_for_select(@bank_names.map{ |obj| [obj['name'], obj['code']] }),
                 { :include_blank =>"Choose One" },
                 :required => true
    %>
  </div>

  <div class="field">
    <%= f.label :contact %>
    <%= f.text_field :contact, required: true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/suppliers/edit.html.erb
<h1>Editing Supplier</h1>

<%= render 'form', supplier: @supplier %>

<%= link_to 'Show', @supplier %> |
<%= link_to 'Back', suppliers_path %>

app/views/suppliers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Suppliers</h1>
<table>
  <thead>
    <tr>
      <th colspan="1"> Supplier Name</th>
      <th colspan="1"> Account</th>
      <th colspan="1"> Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @suppliers.each do |supplier| %>

      <tr>
        <td><%= supplier.name %></td>
        <td><%= supplier.account_number %></td>
        <td><%= link_to 'Show', supplier %></td>
        <td><%= link_to 'Edit', edit_supplier_path(supplier) %></td>
        <td><%= link_to 'New Invoice', new_supplier_invoice_path(supplier.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Supplier', new_supplier_path %>

app/views/suppliers/new.html.erb
<h1>New Supplier</h1>

<%= render 'form', supplier: @supplier %>

<%= link_to 'Back', suppliers_path %>

app/views/suppliers/show.html.erb
<p id="notice"><%= notice %></p>
<table>
  <thead>
  <tr>
    <th colspan="1"> Supplier Name</th>
    <th colspan="2"> Bank Account</th>
    <th colspan="1"> Actions</th>
  </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= @supplier.name %></td>
      <td><%= @supplier.account_number %></td>
      <td><%= link_to 'Invoices', supplier_invoices_path(params[:id]) %></td>
      <td><%= link_to 'Destroy', @supplier, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>

  </tbody>
</table>
<%= link_to 'Edit', edit_supplier_path(@supplier) %> |
<%= link_to 'Back', suppliers_path %>